# SPDX-FileCopyrightText: 2025 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - name: actionlint
        uses: raven-actions/actionlint@v2.1.2
